name: build-docker
on: [push]
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in repository
        run: ls -la

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: List Docker images
        run: docker images

      - name: Push Docker image to Docker Hub
        run: docker push my-image:latest

# - checkout code
# -ls
# - docker build
# - docker images
# - docker push
